services:
    db:
        env_file:
            - .env
        environment:
            - "POSTGRES_USER=${DB_USER}"
            - "POSTGRES_PASSWORD=${DB_PASSWORD}"
            - "POSTGRES_DB=${DB_NAME}"
        image: postgres:16
        container_name: postgres
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data


    backend:
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "${APP_PORT}:${APP_PORT}"
        container_name: onichan-backend
        depends_on:
            - db
        network_mode: "host"


volumes:
    pgdata:
